SERVER_NAME = "127.0.0.1:5000"
# SERVER_NAME = "peanut.one"
SECRET_KEY = "Change me."
MAX_CONTENT_LENGTH = 16777216 # 16 * 1024 * 1024

[FOX]
FILE_NAME_LENGTH = 6

[S3]
ACCESS_KEY = ""
SECRET_KEY = ""
BUCKET_NAME = ""

[TWITCH]
CLIENT_ID = ""
TOKEN = ""
USER_TOKEN = ""

[JMAP]
HOSTNAME = ""
USERNAME = ""
TOKEN = ""
